version: '3'

services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: db
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: